### ISSUE TITLE
Members Password: Symphony Warning: Illegal string offset 'password'

### ISSUE THREAD

**Issue by wdebusschere** [symphonists/importcsv#1]
An error occurred in /Users/xxx/Sites/mortelselector2.weberbeamix.nl/extensions/members/fields/field.memberpassword.php around line 539

Changed the code of members extension in order to get the import done:
 Line 538 field.memberpassword.php

```
$password = trim($data['password']);
to 
$password = $data;

```
Afterwards changed it back, if not the members extension doesn't work 100%.
Is it possible to fix this in the importcsv extension?

**Comment by michael-e** [comment]
Do you use the current extension code (Version 1.0)? There is an import driver for the Member password field, so if import goes wrong, the issue should be fixed there.

**Comment by wdebusschere** [comment]
Yes version 1.0

**Comment by michael-e** [comment]
Can you please post the error that occurs, and example CSV data?

**Comment by wdebusschere** [comment]
"John";"Doe";"john.doe@doe.be";"PBKDF2v1|10000|4b36d5d7c28d0ee6be9f|eOzTAy4QX/zusAXm183k9p/Y1WOgfPczvJqHkEhLoHWY2hgePmCq/A=="


```
Symphony Warning: Illegal string offset 'password'
An error occurred in /Users/wannesdebusschere/Sites/mortelselector2.weberbeamix.nl/extensions/members/fields/field.memberpassword.php around line 539
534             $status = self::__OK__;
535             $required = ($this->get('required') == "yes");
536
537             if(empty($data)) return array();
538
539             $password = trim($data['password']);
540             //$password = $data;
541         
542
```

**Comment by michael-e** [comment]
OK, got it! :-) I will see if I can do some tests.

**Comment by michael-e** [comment]
I have a fix for this and will send a pull request. However, I have two remarks:

1. The importer always assumes that **the password is hashed**. (One might try and check this, but the available hashing algorithms depend on Symphony's Cryptography classes, which are "subject to change". Anyway, this is not the subject of this issue, so I leave this as it is.)
2. The password strength of an imported password will always be `strong`, the length will always be `92` (for PBKDF2 hashing). There is no way to work around this if we import hashed passwords.

**Comment by wdebusschere** [comment]
Thanks Micheal-e for the explanation and fix! 
It's logic that if you export the members section from one symphony you can import the csv into another one.
